[2024-11-23T22:44:00.178+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T22:44:00.196+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_bucket.save_date manual__2024-11-23T22:43:59.133880+00:00 [queued]>
[2024-11-23T22:44:00.206+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_bucket.save_date manual__2024-11-23T22:43:59.133880+00:00 [queued]>
[2024-11-23T22:44:00.207+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-23T22:44:00.222+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_date> on 2024-11-23 22:43:59.133880+00:00
[2024-11-23T22:44:00.233+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=418) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-23T22:44:00.234+0000] {standard_task_runner.py:72} INFO - Started process 420 to run task
[2024-11-23T22:44:00.234+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'create_bucket', 'save_date', 'manual__2024-11-23T22:43:59.133880+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/obs.py', '--cfg-path', '/tmp/tmp4jk8wmaq']
[2024-11-23T22:44:00.235+0000] {standard_task_runner.py:105} INFO - Job 50: Subtask save_date
[2024-11-23T22:44:00.279+0000] {task_command.py:467} INFO - Running <TaskInstance: create_bucket.save_date manual__2024-11-23T22:43:59.133880+00:00 [running]> on host 256f0a297285
[2024-11-23T22:44:00.357+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_bucket' AIRFLOW_CTX_TASK_ID='save_date' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T22:43:59.133880+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-23T22:43:59.133880+00:00'
[2024-11-23T22:44:00.358+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T22:44:10.526+0000] {logging_mixin.py:190} INFO - Create Bucket Failed
[2024-11-23T22:44:10.527+0000] {logging_mixin.py:190} INFO - requestId: 000001935B3266DC47CF00012710197B
[2024-11-23T22:44:10.527+0000] {logging_mixin.py:190} INFO - errorCode: BucketAlreadyExists
[2024-11-23T22:44:10.527+0000] {logging_mixin.py:190} INFO - errorMessage: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
[2024-11-23T22:44:10.527+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-23T22:44:10.538+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T22:44:10.539+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=create_bucket, task_id=save_date, run_id=manual__2024-11-23T22:43:59.133880+00:00, execution_date=20241123T224359, start_date=20241123T224400, end_date=20241123T224410
[2024-11-23T22:44:10.615+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-23T22:44:10.630+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T22:44:10.632+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
