[2024-11-21T21:44:46.653+0000] {processor.py:186} INFO - Started process (PID=3620) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:44:46.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:44:46.656+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:44:46.656+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:44:46.660+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:44:46.659+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:44:46.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:44:46.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.030 seconds
[2024-11-21T21:45:16.880+0000] {processor.py:186} INFO - Started process (PID=3628) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:45:16.881+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:45:16.883+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:16.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:45:16.885+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:16.884+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:45:16.886+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:45:16.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.028 seconds
[2024-11-21T21:45:33.018+0000] {processor.py:186} INFO - Started process (PID=3636) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:45:33.019+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:45:33.021+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:33.020+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:45:33.023+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:33.022+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 21
    credentials = BasicCredentials(ak, sk)
IndentationError: unexpected indent
[2024-11-21T21:45:33.024+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:45:33.041+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.030 seconds
[2024-11-21T21:45:35.033+0000] {processor.py:186} INFO - Started process (PID=3637) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:45:35.034+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:45:35.035+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:35.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:45:35.039+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:35.038+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:45:35.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:45:35.098+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.071 seconds
[2024-11-21T21:45:37.094+0000] {processor.py:186} INFO - Started process (PID=3638) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:45:37.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:45:37.097+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:37.097+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:45:37.101+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:37.100+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:45:37.101+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:45:37.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.050 seconds
[2024-11-21T21:45:39.144+0000] {processor.py:186} INFO - Started process (PID=3639) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:45:39.145+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:45:39.147+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:39.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:45:39.149+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:39.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 21
    def 
        ^
SyntaxError: invalid syntax
[2024-11-21T21:45:39.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:45:39.166+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.027 seconds
[2024-11-21T21:45:44.206+0000] {processor.py:186} INFO - Started process (PID=3640) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:45:44.207+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:45:44.209+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:44.209+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:45:44.212+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:44.211+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 21
    def create_bucket
                     ^
SyntaxError: expected '('
[2024-11-21T21:45:44.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:45:44.229+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.028 seconds
[2024-11-21T21:45:45.223+0000] {processor.py:186} INFO - Started process (PID=3641) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:45:45.224+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:45:45.225+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:45.225+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:45:45.228+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:45.227+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 21
    def create_bucket()
                       ^
SyntaxError: expected ':'
[2024-11-21T21:45:45.229+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:45:45.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.046 seconds
[2024-11-21T21:45:47.280+0000] {processor.py:186} INFO - Started process (PID=3642) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:45:47.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:45:47.283+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:47.283+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:45:47.287+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:47.286+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 22
    credentials = BasicCredentials(ak, sk)
    ^^^^^^^^^^^
IndentationError: expected an indented block after function definition on line 21
[2024-11-21T21:45:47.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:45:47.321+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.046 seconds
[2024-11-21T21:45:48.308+0000] {processor.py:186} INFO - Started process (PID=3643) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:45:48.309+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:45:48.310+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:48.310+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:45:48.313+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:48.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 23
    credentials = BasicCredentials(ak, sk)
    ^^^^^^^^^^^
IndentationError: expected an indented block after function definition on line 21
[2024-11-21T21:45:48.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:45:48.332+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.029 seconds
[2024-11-21T21:45:51.369+0000] {processor.py:186} INFO - Started process (PID=3644) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:45:51.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:45:51.371+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:51.371+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:45:51.374+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:51.373+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:45:51.375+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:45:51.410+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.047 seconds
[2024-11-21T21:45:53.446+0000] {processor.py:186} INFO - Started process (PID=3646) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:45:53.446+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:45:53.449+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:53.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:45:53.452+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:53.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:45:53.453+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:45:53.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.046 seconds
[2024-11-21T21:45:55.509+0000] {processor.py:186} INFO - Started process (PID=3647) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:45:55.510+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:45:55.513+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:55.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:45:55.516+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:55.515+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:45:55.517+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:45:55.532+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.028 seconds
[2024-11-21T21:45:57.541+0000] {processor.py:186} INFO - Started process (PID=3648) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:45:57.541+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:45:57.543+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:57.543+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:45:57.547+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:57.546+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:45:57.547+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:45:57.564+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.028 seconds
[2024-11-21T21:45:58.573+0000] {processor.py:186} INFO - Started process (PID=3649) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:45:58.573+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:45:58.575+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:58.575+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:45:58.579+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:45:58.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:45:58.579+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:45:58.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.028 seconds
[2024-11-21T21:46:01.611+0000] {processor.py:186} INFO - Started process (PID=3650) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:46:01.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:46:01.614+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:01.613+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:46:01.617+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:01.616+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 31
    bucket_name = 'your-bucket-name'  # Replace with your desired bucket name
    ^^^^^^^^^^^
IndentationError: expected an indented block after 'try' statement on line 29
[2024-11-21T21:46:01.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:46:01.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.045 seconds
[2024-11-21T21:46:02.646+0000] {processor.py:186} INFO - Started process (PID=3657) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:46:02.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:46:02.649+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:02.649+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:46:02.652+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:02.651+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 31
    bucket_name = 'your-bucket-name'  # Replace with your desired bucket name
    ^^^^^^^^^^^
IndentationError: expected an indented block after 'try' statement on line 29
[2024-11-21T21:46:02.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:46:02.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.060 seconds
[2024-11-21T21:46:04.693+0000] {processor.py:186} INFO - Started process (PID=3658) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:46:04.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:46:04.696+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:04.695+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:46:04.698+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:04.698+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 34
    create_bucket_request = CreateBucketRequest(
    ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: expected 'except' or 'finally' block
[2024-11-21T21:46:04.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:46:04.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.030 seconds
[2024-11-21T21:46:05.745+0000] {processor.py:186} INFO - Started process (PID=3659) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:46:05.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:46:05.748+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:05.748+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:46:05.751+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:05.750+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 34
    create_bucket_request = CreateBucketRequest(
    ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: expected 'except' or 'finally' block
[2024-11-21T21:46:05.751+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:46:05.767+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.027 seconds
[2024-11-21T21:46:07.776+0000] {processor.py:186} INFO - Started process (PID=3660) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:46:07.777+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:46:07.778+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:07.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:46:07.782+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:07.780+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 39
    response = obs_client.create_bucket(create_bucket_request)
    ^^^^^^^^
SyntaxError: expected 'except' or 'finally' block
[2024-11-21T21:46:07.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:46:07.800+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.029 seconds
[2024-11-21T21:46:10.819+0000] {processor.py:186} INFO - Started process (PID=3661) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:46:10.820+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:46:10.822+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:10.822+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:46:10.825+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:10.824+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 39
    response = obs_client.create_bucket(create_bucket_request)
    ^^^^^^^^
SyntaxError: expected 'except' or 'finally' block
[2024-11-21T21:46:10.826+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:46:10.860+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.046 seconds
[2024-11-21T21:46:12.858+0000] {processor.py:186} INFO - Started process (PID=3662) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:46:12.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:46:12.860+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:12.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:46:12.863+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:12.862+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 39
    response = obs_client.create_bucket(create_bucket_request)
    ^^^^^^^^
SyntaxError: expected 'except' or 'finally' block
[2024-11-21T21:46:12.863+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:46:12.901+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.050 seconds
[2024-11-21T21:46:14.905+0000] {processor.py:186} INFO - Started process (PID=3663) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:46:14.906+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:46:14.909+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:14.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:46:14.911+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:14.911+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 40
    print(f"Bucket created successfully. Response: {response}")
    ^^^^^
SyntaxError: expected 'except' or 'finally' block
[2024-11-21T21:46:14.912+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:46:14.948+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.048 seconds
[2024-11-21T21:46:15.945+0000] {processor.py:186} INFO - Started process (PID=3664) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:46:15.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:46:15.947+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:15.947+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:46:15.950+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:15.949+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 41
    except Exception as e:
SyntaxError: expected 'except' or 'finally' block
[2024-11-21T21:46:15.951+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:46:15.967+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.028 seconds
[2024-11-21T21:46:17.995+0000] {processor.py:186} INFO - Started process (PID=3665) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:46:17.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:46:17.998+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:17.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:46:18.001+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:18.000+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 42
    print(f"Error creating bucket: {e}")
    ^^^^^
IndentationError: expected an indented block after 'except' statement on line 41
[2024-11-21T21:46:18.001+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:46:18.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.028 seconds
[2024-11-21T21:46:19.013+0000] {processor.py:186} INFO - Started process (PID=3666) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:46:19.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:46:19.015+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:19.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:46:19.018+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:19.017+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 43
    finally:
    ^^^^^^^
SyntaxError: invalid syntax
[2024-11-21T21:46:19.019+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:46:19.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.028 seconds
[2024-11-21T21:46:23.075+0000] {processor.py:186} INFO - Started process (PID=3667) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:46:23.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:46:23.078+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:23.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:46:23.081+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:23.080+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 45
    obs_client.close()
    ^^^^^^^^^^
IndentationError: expected an indented block after 'finally' statement on line 43
[2024-11-21T21:46:23.081+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:46:23.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.029 seconds
[2024-11-21T21:46:25.134+0000] {processor.py:186} INFO - Started process (PID=3669) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:46:25.135+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:46:25.137+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:25.137+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:46:25.141+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:25.140+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:46:25.142+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:46:25.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.044 seconds
[2024-11-21T21:46:41.313+0000] {processor.py:186} INFO - Started process (PID=3676) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:46:41.356+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:46:41.358+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:41.358+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:46:41.363+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:41.362+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:46:41.363+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:46:41.380+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.072 seconds
[2024-11-21T21:46:49.378+0000] {processor.py:186} INFO - Started process (PID=3677) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:46:49.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:46:49.381+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:49.380+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:46:49.384+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:46:49.383+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:46:49.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:46:49.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.047 seconds
[2024-11-21T21:47:19.650+0000] {processor.py:186} INFO - Started process (PID=3685) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:47:19.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:47:19.699+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:47:19.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:47:19.702+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:47:19.701+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:47:19.702+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:47:19.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.075 seconds
[2024-11-21T21:47:49.920+0000] {processor.py:186} INFO - Started process (PID=3693) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:47:49.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:47:49.922+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:47:49.922+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:47:49.925+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:47:49.924+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:47:49.926+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:47:49.962+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.047 seconds
[2024-11-21T21:48:20.167+0000] {processor.py:186} INFO - Started process (PID=3701) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:48:20.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:48:20.174+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:48:20.174+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:48:20.177+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:48:20.176+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:48:20.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:48:20.195+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.033 seconds
[2024-11-21T21:48:50.396+0000] {processor.py:186} INFO - Started process (PID=3709) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:48:50.397+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:48:50.400+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:48:50.399+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:48:50.403+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:48:50.402+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:48:50.403+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:48:50.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.029 seconds
[2024-11-21T21:49:20.627+0000] {processor.py:186} INFO - Started process (PID=3717) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:49:20.667+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:49:20.669+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:49:20.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:49:20.672+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:49:20.671+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:49:20.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:49:20.688+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.067 seconds
[2024-11-21T21:49:50.899+0000] {processor.py:186} INFO - Started process (PID=3725) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:49:50.900+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:49:50.902+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:49:50.901+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:49:50.905+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:49:50.904+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:49:50.905+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:49:50.921+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.027 seconds
[2024-11-21T21:50:21.125+0000] {processor.py:186} INFO - Started process (PID=3733) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:50:21.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:50:21.128+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:50:21.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:50:21.131+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:50:21.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:50:21.131+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:50:21.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.048 seconds
[2024-11-21T21:50:51.377+0000] {processor.py:186} INFO - Started process (PID=3741) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:50:51.424+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:50:51.427+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:50:51.426+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:50:51.430+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:50:51.429+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:50:51.430+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:50:51.448+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.076 seconds
[2024-11-21T21:51:21.663+0000] {processor.py:186} INFO - Started process (PID=3749) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:51:21.663+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:51:21.665+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:51:21.665+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:51:21.668+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:51:21.667+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:51:21.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:51:21.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.042 seconds
[2024-11-21T21:51:51.914+0000] {processor.py:186} INFO - Started process (PID=3757) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:51:51.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:51:51.943+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:51:51.943+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:51:51.946+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:51:51.945+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:51:51.946+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:51:51.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.055 seconds
[2024-11-21T21:52:22.166+0000] {processor.py:186} INFO - Started process (PID=3765) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:52:22.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:52:22.169+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:52:22.168+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:52:22.171+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:52:22.170+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:52:22.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:52:22.208+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.047 seconds
[2024-11-21T21:52:52.407+0000] {processor.py:186} INFO - Started process (PID=3773) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:52:52.449+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:52:52.452+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:52:52.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:52:52.455+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:52:52.454+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:52:52.455+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:52:52.472+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.070 seconds
[2024-11-21T21:53:22.664+0000] {processor.py:186} INFO - Started process (PID=3780) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:53:22.664+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:53:22.667+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:53:22.666+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:53:22.669+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:53:22.668+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:53:22.670+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:53:22.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.038 seconds
[2024-11-21T21:53:52.901+0000] {processor.py:186} INFO - Started process (PID=3788) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:53:52.902+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:53:52.903+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:53:52.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:53:52.906+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:53:52.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:53:52.906+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:53:52.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.028 seconds
[2024-11-21T21:54:23.132+0000] {processor.py:186} INFO - Started process (PID=3796) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:54:23.133+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:54:23.134+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:54:23.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:54:23.137+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:54:23.136+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:54:23.137+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:54:23.162+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.034 seconds
[2024-11-21T21:54:53.369+0000] {processor.py:186} INFO - Started process (PID=3804) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:54:53.416+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:54:53.419+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:54:53.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:54:53.421+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:54:53.420+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:54:53.422+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:54:53.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.076 seconds
[2024-11-21T21:54:58.484+0000] {processor.py:186} INFO - Started process (PID=3806) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:54:58.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:54:58.487+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:54:58.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:54:58.490+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:54:58.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:54:58.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:54:58.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.047 seconds
[2024-11-21T21:55:01.527+0000] {processor.py:186} INFO - Started process (PID=3807) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:55:01.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:55:01.531+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:01.530+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:55:01.533+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:01.532+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 21
    ak = 'E0XB2DYJMA1IJNX9TZRH'  # Replace with your Access Key ID
    ^^
IndentationError: expected an indented block after function definition on line 18
[2024-11-21T21:55:01.534+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:55:01.552+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.030 seconds
[2024-11-21T21:55:03.583+0000] {processor.py:186} INFO - Started process (PID=3814) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:55:03.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:55:03.585+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:03.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:55:03.588+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:03.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 25
    credentials = BasicCredentials(ak, sk)
IndentationError: unexpected indent
[2024-11-21T21:55:03.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:55:03.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.026 seconds
[2024-11-21T21:55:05.609+0000] {processor.py:186} INFO - Started process (PID=3815) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:55:05.610+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:55:05.613+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:05.612+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:55:05.616+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:05.615+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 25
    credentials = BasicCredentials(ak, sk)
IndentationError: unexpected indent
[2024-11-21T21:55:05.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:55:05.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.046 seconds
[2024-11-21T21:55:06.643+0000] {processor.py:186} INFO - Started process (PID=3816) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:55:06.644+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:55:06.645+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:06.645+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:55:06.649+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:06.648+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:55:06.649+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:55:06.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.029 seconds
[2024-11-21T21:55:28.830+0000] {processor.py:186} INFO - Started process (PID=3818) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:55:28.884+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:55:28.886+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:28.886+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:55:28.889+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:28.888+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 48
    with DAG('my_dag', default_args=default_args, schedule_interval='@daily', catchup=False) as dag:
                                                                                                    ^
IndentationError: expected an indented block after 'with' statement on line 48
[2024-11-21T21:55:28.890+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:55:28.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.082 seconds
[2024-11-21T21:55:37.987+0000] {processor.py:186} INFO - Started process (PID=3825) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:55:37.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:55:37.989+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:37.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:55:37.992+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:37.991+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 48
    with DAG('create_bucket', default_args=default_args, schedule_interval='@daily', catchup=False) as dag:
                                                                                                           ^
IndentationError: expected an indented block after 'with' statement on line 48
[2024-11-21T21:55:37.993+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:55:38.009+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.027 seconds
[2024-11-21T21:55:41.013+0000] {processor.py:186} INFO - Started process (PID=3826) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:55:41.013+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:55:41.016+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:41.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:55:41.019+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:41.018+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 49
    
    ^
IndentationError: expected an indented block after 'with' statement on line 48
[2024-11-21T21:55:41.019+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:55:41.054+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.047 seconds
[2024-11-21T21:55:54.126+0000] {processor.py:186} INFO - Started process (PID=3827) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:55:54.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:55:54.129+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:54.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:55:54.133+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:55:54.132+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:55:54.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:55:54.169+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.047 seconds
[2024-11-21T21:56:00.218+0000] {processor.py:186} INFO - Started process (PID=3829) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:56:00.219+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:56:00.221+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:56:00.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:56:00.224+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:56:00.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:56:00.225+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:56:00.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.055 seconds
[2024-11-21T21:56:07.329+0000] {processor.py:186} INFO - Started process (PID=3836) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:56:07.376+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:56:07.378+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:56:07.378+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:56:07.381+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:56:07.380+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:56:07.382+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:56:07.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.073 seconds
[2024-11-21T21:56:37.555+0000] {processor.py:186} INFO - Started process (PID=3844) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:56:37.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:56:37.558+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:56:37.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:56:37.561+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:56:37.561+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:56:37.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:56:37.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.028 seconds
[2024-11-21T21:56:38.583+0000] {processor.py:186} INFO - Started process (PID=3845) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:56:38.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:56:38.586+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:56:38.586+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:56:38.590+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:56:38.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:56:38.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:56:38.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.029 seconds
[2024-11-21T21:56:52.690+0000] {processor.py:186} INFO - Started process (PID=3846) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:56:52.691+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:56:52.693+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:56:52.692+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:56:52.696+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:56:52.695+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:56:52.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:56:52.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.027 seconds
[2024-11-21T21:57:14.858+0000] {processor.py:186} INFO - Started process (PID=3854) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:57:14.859+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:57:14.861+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:57:14.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:57:14.865+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:57:14.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:57:14.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:57:14.883+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.030 seconds
[2024-11-21T21:57:15.868+0000] {processor.py:186} INFO - Started process (PID=3855) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:57:15.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:57:15.871+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:57:15.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:57:15.875+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:57:15.874+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:57:15.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:57:15.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.030 seconds
[2024-11-21T21:57:22.954+0000] {processor.py:186} INFO - Started process (PID=3856) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:57:22.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:57:22.957+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:57:22.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:57:22.960+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:57:22.959+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:57:22.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:57:22.976+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.027 seconds
[2024-11-21T21:57:35.063+0000] {processor.py:186} INFO - Started process (PID=3864) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:57:35.063+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:57:35.065+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:57:35.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:57:35.069+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:57:35.068+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:57:35.069+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:57:35.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.030 seconds
[2024-11-21T21:58:05.266+0000] {processor.py:186} INFO - Started process (PID=3872) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:58:05.301+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:58:05.304+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:58:05.304+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:58:05.307+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:58:05.306+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:58:05.307+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:58:05.324+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.063 seconds
[2024-11-21T21:58:35.542+0000] {processor.py:186} INFO - Started process (PID=3880) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:58:35.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:58:35.545+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:58:35.545+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:58:35.548+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:58:35.547+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:58:35.548+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:58:35.584+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.047 seconds
[2024-11-21T21:59:05.744+0000] {processor.py:186} INFO - Started process (PID=3903) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:59:05.745+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:59:05.748+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:59:05.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:59:05.753+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:59:05.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:59:05.753+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:59:05.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.036 seconds
[2024-11-21T21:59:35.941+0000] {processor.py:186} INFO - Started process (PID=3911) to work on /opt/airflow/dags/obs.py
[2024-11-21T21:59:35.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T21:59:35.944+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:59:35.943+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T21:59:35.947+0000] {logging_mixin.py:190} INFO - [2024-11-21T21:59:35.946+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 1, in <module>
    from huaweicloudsdkcore.auth.credentials import BasicCredentials
ModuleNotFoundError: No module named 'huaweicloudsdkcore'
[2024-11-21T21:59:35.947+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T21:59:35.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.042 seconds
[2024-11-21T22:00:06.146+0000] {processor.py:186} INFO - Started process (PID=3953) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:00:06.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:00:06.195+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:00:06.195+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:00:06.269+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:00:06.268+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:00:06.269+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:00:06.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.145 seconds
[2024-11-21T22:00:36.447+0000] {processor.py:186} INFO - Started process (PID=3961) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:00:36.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:00:36.450+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:00:36.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:00:36.472+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:00:36.471+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:00:36.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:00:36.489+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.050 seconds
[2024-11-21T22:01:06.661+0000] {processor.py:186} INFO - Started process (PID=3969) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:01:06.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:01:06.709+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:01:06.708+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:01:06.734+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:01:06.733+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:01:06.734+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:01:06.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.100 seconds
[2024-11-21T22:02:04.733+0000] {processor.py:186} INFO - Started process (PID=60) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:02:04.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:02:04.737+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:02:04.736+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:02:04.764+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:02:04.763+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:02:04.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:02:04.784+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.057 seconds
[2024-11-21T22:02:34.991+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:02:34.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:02:34.994+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:02:34.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:02:35.014+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:02:35.014+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:02:35.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:02:35.031+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.045 seconds
[2024-11-21T22:03:05.245+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:03:05.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:03:05.295+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:03:05.295+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:03:05.316+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:03:05.315+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:03:05.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:03:05.333+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.092 seconds
[2024-11-21T22:03:35.546+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:03:35.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:03:35.596+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:03:35.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:03:35.617+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:03:35.616+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:03:35.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:03:35.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.092 seconds
[2024-11-21T22:04:05.848+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:04:05.895+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:04:05.897+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:04:05.896+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:04:05.918+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:04:05.917+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:04:05.919+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:04:05.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.094 seconds
[2024-11-21T22:04:36.153+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:04:36.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:04:36.202+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:04:36.202+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:04:36.353+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:04:36.352+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:04:36.354+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:04:36.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.256 seconds
[2024-11-21T22:05:06.627+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:05:06.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:05:06.677+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:05:06.677+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:05:06.829+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:05:06.828+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:05:06.830+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:05:06.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.221 seconds
[2024-11-21T22:05:37.067+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:05:37.068+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:05:37.070+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:05:37.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:05:37.090+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:05:37.089+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:05:37.090+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:05:37.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.044 seconds
[2024-11-21T22:06:07.330+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:06:07.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:06:07.334+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:06:07.333+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:06:07.354+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:06:07.353+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:06:07.354+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:06:07.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.045 seconds
[2024-11-21T22:06:37.585+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:06:37.586+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:06:37.588+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:06:37.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:06:37.608+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:06:37.608+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:06:37.609+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:06:37.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.046 seconds
[2024-11-21T22:07:07.850+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:07:07.897+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:07:07.900+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:07:07.900+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:07:07.921+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:07:07.920+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:07:07.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:07:07.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.092 seconds
[2024-11-21T22:07:38.160+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:07:38.207+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:07:38.211+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:07:38.210+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:07:38.231+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:07:38.231+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:07:38.232+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:07:38.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.092 seconds
[2024-11-21T22:08:08.463+0000] {processor.py:186} INFO - Started process (PID=156) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:08:08.509+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:08:08.512+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:08:08.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:08:08.534+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:08:08.533+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:08:08.534+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:08:08.550+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.092 seconds
[2024-11-21T22:08:38.769+0000] {processor.py:186} INFO - Started process (PID=170) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:08:38.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:08:38.819+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:08:38.819+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:08:38.841+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:08:38.841+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:08:38.842+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:08:38.860+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.096 seconds
[2024-11-21T22:09:09.079+0000] {processor.py:186} INFO - Started process (PID=178) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:09:09.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:09:09.130+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:09:09.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:09:09.150+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:09:09.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:09:09.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:09:09.166+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.092 seconds
[2024-11-21T22:09:39.388+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:09:39.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:09:39.438+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:09:39.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:09:39.458+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:09:39.457+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:09:39.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:09:39.475+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.092 seconds
[2024-11-21T22:10:09.694+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:10:09.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:10:09.745+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:10:09.744+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:10:09.765+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:10:09.764+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:10:09.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:10:09.781+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.092 seconds
[2024-11-21T22:10:40.001+0000] {processor.py:186} INFO - Started process (PID=202) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:10:40.048+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:10:40.051+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:10:40.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:10:40.071+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:10:40.070+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:10:40.072+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:10:40.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.093 seconds
[2024-11-21T22:11:10.304+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:11:10.305+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:11:10.307+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:11:10.307+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:11:10.327+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:11:10.326+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:11:10.327+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:11:10.343+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.044 seconds
[2024-11-21T22:11:40.565+0000] {processor.py:186} INFO - Started process (PID=218) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:11:40.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:11:40.568+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:11:40.568+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:11:40.590+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:11:40.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:11:40.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:11:40.606+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.046 seconds
[2024-11-21T22:12:10.831+0000] {processor.py:186} INFO - Started process (PID=226) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:12:10.900+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:12:10.903+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:12:10.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:12:10.923+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:12:10.922+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:12:10.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:12:10.939+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.113 seconds
[2024-11-21T22:12:41.161+0000] {processor.py:186} INFO - Started process (PID=234) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:12:41.208+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:12:41.211+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:12:41.210+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:12:41.232+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:12:41.231+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:12:41.232+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:12:41.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.092 seconds
[2024-11-21T22:13:11.462+0000] {processor.py:186} INFO - Started process (PID=242) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:13:11.509+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:13:11.512+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:13:11.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:13:11.532+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:13:11.531+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:13:11.532+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:13:11.548+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.092 seconds
[2024-11-21T22:13:41.766+0000] {processor.py:186} INFO - Started process (PID=250) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:13:41.814+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:13:41.817+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:13:41.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:13:41.837+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:13:41.837+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:13:41.838+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:13:41.853+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.092 seconds
[2024-11-21T22:14:12.078+0000] {processor.py:186} INFO - Started process (PID=258) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:14:12.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:14:12.128+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:14:12.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:14:12.148+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:14:12.148+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:14:12.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:14:12.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.092 seconds
[2024-11-21T22:14:42.379+0000] {processor.py:186} INFO - Started process (PID=266) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:14:42.424+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:14:42.427+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:14:42.427+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:14:42.447+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:14:42.446+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:14:42.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:14:42.464+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.090 seconds
[2024-11-21T22:15:12.681+0000] {processor.py:186} INFO - Started process (PID=274) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:15:12.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:15:12.764+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:15:12.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:15:12.784+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:15:12.784+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:15:12.785+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:15:12.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.124 seconds
[2024-11-21T22:15:43.007+0000] {processor.py:186} INFO - Started process (PID=282) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:15:43.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:15:43.010+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:15:43.009+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:15:43.030+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:15:43.029+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:15:43.030+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:15:43.046+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.044 seconds
[2024-11-21T22:16:13.264+0000] {processor.py:186} INFO - Started process (PID=290) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:16:13.265+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:16:13.268+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:16:13.267+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:16:13.292+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:16:13.291+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:16:13.293+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:16:13.311+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.053 seconds
[2024-11-21T22:16:43.526+0000] {processor.py:186} INFO - Started process (PID=298) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:16:43.527+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:16:43.530+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:16:43.530+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:16:43.550+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:16:43.549+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:16:43.550+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:16:43.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.046 seconds
[2024-11-21T22:17:13.787+0000] {processor.py:186} INFO - Started process (PID=306) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:17:13.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:17:13.789+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:17:13.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:17:13.810+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:17:13.809+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:17:13.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:17:13.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.044 seconds
[2024-11-21T22:17:44.041+0000] {processor.py:186} INFO - Started process (PID=314) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:17:44.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:17:44.044+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:17:44.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:17:44.066+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:17:44.065+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:17:44.066+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:17:44.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.045 seconds
[2024-11-21T22:18:14.301+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:18:14.302+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:18:14.305+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:18:14.304+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:18:14.325+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:18:14.324+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:18:14.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:18:14.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.045 seconds
[2024-11-21T22:18:44.553+0000] {processor.py:186} INFO - Started process (PID=330) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:18:44.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:18:44.556+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:18:44.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:18:44.576+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:18:44.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:18:44.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:18:44.594+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.046 seconds
[2024-11-21T22:19:14.818+0000] {processor.py:186} INFO - Started process (PID=338) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:19:14.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:19:14.822+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:19:14.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:19:14.843+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:19:14.843+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:19:14.844+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:19:14.859+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.047 seconds
[2024-11-21T22:19:45.082+0000] {processor.py:186} INFO - Started process (PID=346) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:19:45.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:19:45.085+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:19:45.085+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:19:45.105+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:19:45.104+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:19:45.105+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:19:45.122+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.045 seconds
[2024-11-21T22:20:15.336+0000] {processor.py:186} INFO - Started process (PID=354) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:20:15.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:20:15.339+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:20:15.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:20:15.359+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:20:15.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:20:15.360+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:20:15.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.044 seconds
[2024-11-21T22:20:45.600+0000] {processor.py:186} INFO - Started process (PID=362) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:20:45.600+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:20:45.603+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:20:45.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:20:45.623+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:20:45.622+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:20:45.623+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:20:45.639+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.044 seconds
[2024-11-21T22:21:15.860+0000] {processor.py:186} INFO - Started process (PID=370) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:21:15.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:21:15.863+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:21:15.863+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:21:15.885+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:21:15.884+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:21:15.886+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:21:15.902+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.047 seconds
[2024-11-21T22:21:46.110+0000] {processor.py:186} INFO - Started process (PID=378) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:21:46.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:21:46.113+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:21:46.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:21:46.135+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:21:46.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:21:46.136+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:21:46.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.047 seconds
[2024-11-21T22:22:16.412+0000] {processor.py:186} INFO - Started process (PID=386) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:22:16.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:22:16.463+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:22:16.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:22:16.486+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:22:16.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:22:16.486+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:22:16.510+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.104 seconds
[2024-11-21T22:22:46.765+0000] {processor.py:186} INFO - Started process (PID=394) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:22:46.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:22:46.769+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:22:46.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:22:46.792+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:22:46.791+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:22:46.793+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:22:46.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.055 seconds
[2024-11-21T22:23:17.067+0000] {processor.py:186} INFO - Started process (PID=402) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:23:17.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:23:17.117+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:23:17.117+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:23:17.138+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:23:17.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:23:17.139+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:23:17.158+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.096 seconds
[2024-11-21T22:23:47.427+0000] {processor.py:186} INFO - Started process (PID=410) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:23:47.428+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:23:47.432+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:23:47.432+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:23:47.460+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:23:47.459+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:23:47.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:23:47.485+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.065 seconds
[2024-11-21T22:24:17.749+0000] {processor.py:186} INFO - Started process (PID=418) to work on /opt/airflow/dags/obs.py
[2024-11-21T22:24:17.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/obs.py for tasks to queue
[2024-11-21T22:24:17.799+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:24:17.798+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/obs.py
[2024-11-21T22:24:17.823+0000] {logging_mixin.py:190} INFO - [2024-11-21T22:24:17.822+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/obs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/obs.py", line 2, in <module>
    from huaweicloudsdkobs.v3.obs_client import ObsClient
ModuleNotFoundError: No module named 'huaweicloudsdkobs.v3'
[2024-11-21T22:24:17.823+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/obs.py
[2024-11-21T22:24:17.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/obs.py took 0.101 seconds
