[2024-11-23T22:45:58.821+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T22:45:58.838+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_bucket.save_date manual__2024-11-23T22:45:57.321286+00:00 [queued]>
[2024-11-23T22:45:58.847+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_bucket.save_date manual__2024-11-23T22:45:57.321286+00:00 [queued]>
[2024-11-23T22:45:58.847+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-23T22:45:58.860+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_date> on 2024-11-23 22:45:57.321286+00:00
[2024-11-23T22:45:58.867+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=449) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-23T22:45:58.869+0000] {standard_task_runner.py:72} INFO - Started process 451 to run task
[2024-11-23T22:45:58.869+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'create_bucket', 'save_date', 'manual__2024-11-23T22:45:57.321286+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/obs.py', '--cfg-path', '/tmp/tmp719ku8ma']
[2024-11-23T22:45:58.870+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask save_date
[2024-11-23T22:45:58.913+0000] {task_command.py:467} INFO - Running <TaskInstance: create_bucket.save_date manual__2024-11-23T22:45:57.321286+00:00 [running]> on host 256f0a297285
[2024-11-23T22:45:58.992+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_bucket' AIRFLOW_CTX_TASK_ID='save_date' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T22:45:57.321286+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-23T22:45:57.321286+00:00'
[2024-11-23T22:45:58.993+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T22:46:05.634+0000] {logging_mixin.py:190} INFO - Create Bucket Failed
[2024-11-23T22:46:05.634+0000] {logging_mixin.py:190} INFO - requestId: 000001935B34297444D4B183E0ECEA69
[2024-11-23T22:46:05.634+0000] {logging_mixin.py:190} INFO - errorCode: InvalidBucketName
[2024-11-23T22:46:05.635+0000] {logging_mixin.py:190} INFO - errorMessage: The specified bucket is not valid.
[2024-11-23T22:46:05.635+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-23T22:46:05.645+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T22:46:05.645+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=create_bucket, task_id=save_date, run_id=manual__2024-11-23T22:45:57.321286+00:00, execution_date=20241123T224557, start_date=20241123T224558, end_date=20241123T224605
[2024-11-23T22:46:05.740+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-23T22:46:05.755+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T22:46:05.756+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
