[2024-11-22T17:02:29.256+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T17:02:29.278+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.check_file_exists scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T17:02:29.289+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.check_file_exists scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T17:02:29.290+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2024-11-22T17:02:29.304+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): check_file_exists> on 2024-11-21 00:00:00+00:00
[2024-11-22T17:02:29.314+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=362) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-22T17:02:29.315+0000] {standard_task_runner.py:72} INFO - Started process 363 to run task
[2024-11-22T17:02:29.317+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'check_file_exists', 'scheduled__2024-11-21T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpww9d_u5a']
[2024-11-22T17:02:29.318+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask check_file_exists
[2024-11-22T17:02:29.367+0000] {task_command.py:467} INFO - Running <TaskInstance: my_dag.check_file_exists scheduled__2024-11-21T00:00:00+00:00 [running]> on host f16f6e21f449
[2024-11-22T17:02:29.450+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='check_file_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T00:00:00+00:00'
[2024-11-22T17:02:29.450+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-22T17:02:29.463+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-22T17:02:29.464+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Checking data..."']
[2024-11-22T17:02:29.478+0000] {subprocess.py:99} INFO - Output:
[2024-11-22T17:02:29.480+0000] {subprocess.py:106} INFO - Checking data...
[2024-11-22T17:02:29.481+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-11-22T17:02:29.507+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-22T17:02:29.508+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=check_file_exists, run_id=scheduled__2024-11-21T00:00:00+00:00, execution_date=20241121T000000, start_date=20241122T170229, end_date=20241122T170229
[2024-11-22T17:02:29.530+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-22T17:02:29.553+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-22T17:02:29.554+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
